f=open("n1.txt","a+")
print("name ",f.name)
print("mode ",f.mode)
print("encodeing ",f.encoding)
print("readable ",f.readable())
print("writable ",f.writable())
print(f.closed)
f.close()
print(f.closed)